# These are supported funding model platforms

github: [geauxweisbeck4, tar-heel-dev-studio]
patreon: geauxweisbeck4
open_collective: geauxweisbeck4
ko_fi: geauxweisbeck4
buy_me_a_coffee: geauxweisbeck4
custom: https://cashapp.com/geauxweisbeck
